# Generated by Django 6.1.1 on 2026-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blinkit',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('cart', models.TextField()),
                ('phone_no', models.IntegerField(primary_key=True, serialize=False)),
                ('order_history', models.TextField()),
                ('total_amtspent', models.IntegerField()),
                ('alternative_phoneno', models.IntegerField()),
            ],
        ),
    ]
